apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-service:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: MONGO_DB_NAME
              value: "users"
            - name: NODE_ENV
              value: development

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
