FROM node:23-alpine
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app

# Copy pnpm files first for caching
COPY pnpm-lock.yaml package.json ./
RUN pnpm install --frozen-lockfile

# Copy all files (except those in .dockerignore)
COPY . .

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

EXPOSE 3000 9229
CMD ["pnpm", "dev", "--hostname", "0.0.0.0"]