version: "3.8"

services:
  auth-service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGO_DB_NAME=users
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - JWT_SECRET=rqwerwqerwqr
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: auth_db
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  redis:
    container_name: auth_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
