apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
        - image: user:dev
          imagePullPolicy: Never
          name: user
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: MONGO_DB_NAME
              value: "users"
            - name: MONGO_HOST
              value: "auth-db"
            - name: MONGO_PORT
              value: "27017"
            - name: NODE_ENV
              value: development
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_QUEUE
              value: "user"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user
  name: user
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: user
status:
  loadBalancer: {}
